apiVersion: v1
kind: PersistentVolume
metadata:
  name: envoy-config
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/envoy"
