---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.22.0
    helm:
      releaseName: prometheus
      valuesObject:
        fullnameOverride: prometheus

        ################################################
        ##### prometheus config
        ################################################

        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        prometheus-node-exporter:
          enabled: false
  
        prometheus:
          enabled: true
          containerPort: 8080
          containerPortName: metrics

        # scrape_configs:
        #   - job_name: prometheus-scrape
        #     scrape_interval: 1m # default
        #     scrape_timeout: 10s # default
        #     metrics_path: /metrics #default
        #     scheme: http # default
