---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: 
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.21.0 # https://artifacthub.io/packages/helm/prometheus-community/prometheus
    helm:
      releaseName: prometheus
      valuesObject:
        # https://artifacthub.io/packages/helm/prometheus-community/prometheus?modal=values
        fullnameOverride: prometheus

        ################################################
        ##### Prometheus config
        ################################################
