---
# Grafana helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.2.4 # https://artifacthub.io/packages/helm/grafana/grafana
    helm:
      releaseName: grafana
